insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('test@gmail.com', 'test', 'hsiss0', 'Hank', 'Siss', '459 Meadow Valley Hill', '2262697715', 2.19);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('test2@gmail.com', 'test2', 'bberndtsson1', 'Barbee', 'Berndtsson', '27 Knutson Trail', '5736867686', 0.06);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ahaldenby2@cocolog-nifty.com', 'IbcWqAk7iqL', 'ahaldenby2', 'Allard', 'Haldenby', '36891 Summit Circle', '5889862587', 2.26);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('klobbe3@cnet.com', 'FqsqSB1Ky', 'klobbe3', 'Kirsteni', 'Lobbe', '50311 Main Alley', '7827940970', 3.55);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dlegrove4@samsung.com', 'VrfipQ', 'dlegrove4', 'Dill', 'Le Grove', '1087 Forster Court', '4391889557', 2.02);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('hscolding5@last.fm', 'exAOB9RF6t', 'hscolding5', 'Hillery', 'Scolding', '04 Jenifer Drive', '8132546942', 4.42);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dscarffe6@nyu.edu', 'VgH5Xd', 'dscarffe6', 'Duffy', 'Scarffe', '7420 Eliot Plaza', '6017251026', 4.66);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('gpape7@ehow.com', 'qcUmRtoC', 'gpape7', 'Giuditta', 'Pape', '008 Arrowood Trail', '8195752996', 1.2);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('alapthorne8@buzzfeed.com', 'PyvgNmM', 'alapthorne8', 'Ange', 'Lapthorne', '0 Hollow Ridge Crossing', '4493792049', 3.29);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('mantonignetti9@jiathis.com', 'UzYzqkNXkl', 'mantonignetti9', 'Maris', 'Antonignetti', '5 John Wall Plaza', '1448780250', 1.24);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('pipgravea@abc.net.au', 'tCCpzzU', 'pipgravea', 'Paule', 'Ipgrave', '3 Springview Junction', '5121526426', 1.48);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('aleahairb@list-manage.com', 'xjHtOL', 'aleahairb', 'Allissa', 'Leahair', '1 Green Ridge Plaza', '3945283642', 0.84);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dsmithendc@1688.com', 'x1mSluHwLRu4', 'dsmithendc', 'Dixie', 'Smithend', '8 Carioca Drive', '3689287116', 4.81);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('acoxd@sourceforge.net', '3uuubyQeB', 'acoxd', 'Antonio', 'Cox', '9508 Saint Paul Park', '5528265587', 1.84);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dphillote@google.co.uk', 'ZnEPk6mH30v', 'dphillote', 'Douglas', 'Phillot', '2 South Plaza', '4704501324', 0.75);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('agemmellf@wikipedia.org', 'eywWOPP', 'agemmellf', 'Amery', 'Gemmell', '1 Gateway Street', '2818580384', 1.28);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('awitherowg@cocolog-nifty.com', '5pEAHQsmhwB', 'awitherowg', 'Augusta', 'Witherow', '1985 Tennyson Place', '3048363563', 4.02);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ggiuronh@state.tx.us', 'A78f40y', 'ggiuronh', 'Gradey', 'Giuron', '7 Roth Parkway', '5227777321', 1.02);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('fhugki@mit.edu', 'BqHXFuH', 'fhugki', 'Fowler', 'Hugk', '60523 Shopko Crossing', '4111344233', 4.6);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ralekhovj@chicagotribune.com', 'Ou9jM93u', 'ralekhovj', 'Ruggiero', 'Alekhov', '66 Waywood Center', '1568935611', 4.58);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ksaffillk@soup.io', 'FErptAT', 'ksaffillk', 'Karry', 'Saffill', '8311 Carpenter Alley', '2744801687', 1.95);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ceastridgel@gnu.org', 'QRwF9pLmBcy', 'ceastridgel', 'Carrie', 'Eastridge', '44 Anderson Alley', '4998753708', 4.23);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('cwartnabym@skyrock.com', 'VXiKWnBI25hB', 'cwartnabym', 'Cacilie', 'Wartnaby', '70265 Northwestern Junction', '1584777459', 1.61);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('syakuntsovn@pagesperso-orange.fr', 'i78eVSsiXb', 'syakuntsovn', 'Seamus', 'Yakuntsov', '5331 Westerfield Court', '6516703842', 2.37);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('odematteio@163.com', '36QdWzn4c', 'odematteio', 'Oran', 'De Mattei', '09948 Surrey Lane', '3001205031', 3.65);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('tbugbirdp@google.com.br', 'DBJUgp8ez', 'tbugbirdp', 'Tabby', 'Bugbird', '8092 Ohio Pass', '5154353053', 3.04);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ccageq@huffingtonpost.com', 'QfWgcf7achiE', 'ccageq', 'Carson', 'Cage', '43306 Chive Park', '1699880622', 0.23);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('trawcliffer@rakuten.co.jp', 'aBDaphJ8J', 'trawcliffer', 'Twila', 'Rawcliffe', '94037 Johnson Drive', '7023830094', 4.04);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ggottschalks@slate.com', 'h3s2Ds', 'ggottschalks', 'Gordan', 'Gottschalk', '8525 Gulseth Junction', '6764267126', 4.76);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dharwoodt@clickbank.net', 'cST3UfS', 'dharwoodt', 'Deloria', 'Harwood', '69069 New Castle Plaza', '6802312425', 2.89);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('jpostanu@nyu.edu', 'hkIgQeIEr', 'jpostanu', 'Jeffie', 'Postan', '31166 Sullivan Lane', '5522685546', 2.24);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ccreamv@jimdo.com', 'dUkfomLHApS', 'ccreamv', 'Cathlene', 'Cream', '9152 Sommers Pass', '8949931877', 0.77);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('wgauntw@zdnet.com', 'zN1b5PsgRl36', 'wgauntw', 'Waverley', 'Gaunt', '40 Towne Place', '6288966445', 3.63);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('fhamelx@miitbeian.gov.cn', 'MhD42x3z0F', 'fhamelx', 'Fredi', 'Hamel', '533 Dovetail Lane', '3896613227', 1.26);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('kpetterseny@usgs.gov', 'MpPxYm32KrQW', 'kpetterseny', 'Karla', 'Pettersen', '953 Buhler Trail', '3633920627', 4.88);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('isweetenhamz@abc.net.au', 'bXXvA2b', 'isweetenhamz', 'Ilka', 'Sweetenham', '0 Muir Point', '5683882241', 4.45);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('mrobe10@technorati.com', 'Oji5Rf', 'mrobe10', 'Mallissa', 'Robe', '7801 Vernon Junction', '8627507733', 1.1);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('zcleyne11@clickbank.net', 'ThcwBiX9', 'zcleyne11', 'Zenia', 'Cleyne', '42 Hayes Center', '9139533738', 3.27);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('czeale12@seesaa.net', 'jTkNF1', 'czeale12', 'Cobbie', 'Zeale', '6606 Sage Pass', '5008707136', 4.49);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('mjocic13@rakuten.co.jp', 'SURsdtZoHLfy', 'mjocic13', 'Marcellina', 'Jocic', '6666 Dennis Parkway', '6043451695', 3.52);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('pgonet14@livejournal.com', '44Xy9ZFVy', 'pgonet14', 'Paul', 'Gonet', '2 Northfield Crossing', '3886436002', 4.15);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('pmacmaster15@eepurl.com', 'PT5t6QXV7n', 'pmacmaster15', 'Philippa', 'MacMaster', '790 Mallory Crossing', '9553284120', 2.22);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('whunsworth16@china.com.cn', 'zKCC8iRvG7i', 'whunsworth16', 'Wallis', 'Hunsworth', '9 Delaware Alley', '2505175720', 1.43);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('gszymoni17@mediafire.com', 'uAAU9SpGOiZD', 'gszymoni17', 'Gretchen', 'Szymoni', '74650 Marcy Drive', '4808897024', 2.72);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('lmurrhardt18@usnews.com', 'UsBj2vvt', 'lmurrhardt18', 'Lanni', 'Murrhardt', '4 Glendale Terrace', '9594939455', 2.36);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('gjacox19@storify.com', 'yNkJt5ESR1O', 'gjacox19', 'Gianna', 'Jacox', '7693 Donald Park', '6564466229', 4.68);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ellewhellin1a@zimbio.com', 'hNVhmBTkw', 'ellewhellin1a', 'Elka', 'Llewhellin', '3 Mifflin Junction', '7589162490', 3.87);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dlowbridge1b@dell.com', '8ZVWft9by80a', 'dlowbridge1b', 'Dacie', 'Lowbridge', '6 3rd Plaza', '7721853759', 3.92);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('wbruneau1c@cisco.com', 'fAsaqzK2Tjtz', 'wbruneau1c', 'Wyatt', 'Bruneau', '04217 Sullivan Trail', '1989215289', 0.32);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('bepinoy1d@exblog.jp', 'HDK2dBDDXWA', 'bepinoy1d', 'Bernadine', 'Epinoy', '3959 Raven Avenue', '4286501617', 4.06);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('aphlippi1e@1688.com', 'Ce80wQ2iW', 'aphlippi1e', 'Austin', 'Phlippi', '25815 Lakewood Gardens Way', '6841643170', 1.54);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('hyouster1f@pen.io', 'fw6J4N2LCg', 'hyouster1f', 'Hillier', 'Youster', '0 Cascade Trail', '9497551659', 4.44);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dguilder1g@chronoengine.com', 'zdmNzDh', 'dguilder1g', 'Darcee', 'Guilder', '8976 Weeping Birch Drive', '3954244836', 4.36);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('cspaven1h@google.com.br', 'M1hXgxjnEBc', 'cspaven1h', 'Clarine', 'Spaven', '1299 Barby Avenue', '3201405052', 4.05);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('bnewbury1i@bing.com', '1BAmLIaQT40', 'bnewbury1i', 'Birgitta', 'Newbury', '56561 Myrtle Avenue', '2287012476', 4.98);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('nwasiel1j@slideshare.net', 'g1HaP8L8Y', 'nwasiel1j', 'Norri', 'Wasiel', '52 Hoepker Place', '8656543309', 1.51);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('hdancer1k@delicious.com', 'HsyczG', 'hdancer1k', 'Hertha', 'Dancer', '8160 Ramsey Plaza', '8076527539', 3.38);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('reastop1l@msn.com', 'xpZYs2KefYSV', 'reastop1l', 'Roselle', 'Eastop', '4482 Eastwood Drive', '2492462968', 1.71);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('esilverwood1m@ihg.com', 'AJzo6k', 'esilverwood1m', 'Eli', 'Silverwood', '1 3rd Place', '9951791790', 3.01);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('lmartyn1n@weebly.com', 'EXAQzH7EpOLu', 'lmartyn1n', 'Les', 'Martyn', '35 Amoth Parkway', '9787182078', 2.52);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('flafflina1o@webs.com', 'T0uM8sfrUEW', 'flafflina1o', 'Freddie', 'Lafflina', '0684 Ridge Oak Trail', '4855807199', 2.82);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ggebhard1p@umich.edu', 'a2rd0IkTv', 'ggebhard1p', 'Glenine', 'Gebhard', '65740 Bay Hill', '7008078288', 1.13);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('thoy1q@state.tx.us', 'NdCS5N', 'thoy1q', 'Teresa', 'Hoy', '723 Rigney Street', '8128568430', 0.69);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('mgrigor1r@nationalgeographic.com', 'KI9PTl', 'mgrigor1r', 'Madison', 'Grigor', '980 Dexter Terrace', '8802074614', 2.7);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('itothe1s@jugem.jp', 'sLENm7bi', 'itothe1s', 'Ian', 'Tothe', '344 Ruskin Avenue', '7376317760', 4.1);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('mfalcus1t@a8.net', '2cT84Gl7', 'mfalcus1t', 'Meaghan', 'Falcus', '09 Crowley Way', '8763571885', 1.39);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('lbirks1u@npr.org', 'tHcf9SGjK', 'lbirks1u', 'Leigha', 'Birks', '12548 Sage Lane', '2518726832', 0.36);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('nrydzynski1v@chicagotribune.com', 'IctNZqAeIBuY', 'nrydzynski1v', 'Nichols', 'Rydzynski', '879 Jana Junction', '6657715678', 2.54);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('lsetch1w@kickstarter.com', 'TWNTuYxFf', 'lsetch1w', 'Lovell', 'Setch', '894 Sauthoff Lane', '4998561576', 4.58);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('cbiset1x@vinaora.com', 'yfPjLwsYBRI6', 'cbiset1x', 'Corine', 'Biset', '3 Twin Pines Circle', '6211957458', 2.15);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('gquarterman1y@a8.net', 'tJGnVd', 'gquarterman1y', 'Guglielma', 'Quarterman', '3668 Talisman Center', '1728402709', 3.86);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('msmullen1z@wisc.edu', 'WKZuKbM0MEp', 'msmullen1z', 'Marsh', 'Smullen', '11542 Artisan Terrace', '7801255218', 4.29);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('cweatherburn20@vk.com', 'cEEKPGqoU6M', 'cweatherburn20', 'Claudine', 'Weatherburn', '68 Stephen Park', '4472285633', 2.94);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ctatam21@google.it', 'PWhHiMGK', 'ctatam21', 'Claudetta', 'Tatam', '59 Westerfield Lane', '1377814376', 1.53);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('arance22@vk.com', 'h0C1kSOh3', 'arance22', 'Aili', 'Rance', '52 Mallory Alley', '9223190912', 0.04);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('gkarel23@aboutads.info', 'EXvTfgIdYvk', 'gkarel23', 'Georgetta', 'Karel', '24 Dahle Terrace', '2919704947', 3.48);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('wizatson24@google.de', 'uwSsrDVezs', 'wizatson24', 'Wilhelm', 'Izatson', '948 Rockefeller Park', '3895781872', 4.2);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('mbenwell25@eepurl.com', 'XMIrSNSGXE', 'mbenwell25', 'Milly', 'Benwell', '89 Coolidge Crossing', '8833384525', 3.14);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('agrills26@spiegel.de', 'kP785sU1D', 'agrills26', 'Agneta', 'Grills', '093 Gerald Road', '7487566976', 2.29);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('gpingstone27@google.co.jp', 'Bx9xfd0pdA', 'gpingstone27', 'Griz', 'Pingstone', '2241 4th Road', '5308894492', 2.7);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('crime28@webnode.com', 'k0VOxna8', 'crime28', 'Constance', 'Rime', '5 Dakota Alley', '3031262390', 2.85);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('purvoy29@wisc.edu', 'N4KNiN2', 'purvoy29', 'Paquito', 'Urvoy', '3 Mayfield Trail', '3177068958', 3.01);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('jbrindle2a@sfgate.com', 'lJCVHWmgIPC4', 'jbrindle2a', 'Joshuah', 'Brindle', '94 Delladonna Lane', '6285469416', 0.36);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('balyukin2b@aboutads.info', 'xNBhvMy', 'balyukin2b', 'Brigit', 'Alyukin', '41645 Rigney Crossing', '6769884078', 2.17);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('canniwell2c@jalbum.net', '3l2cNDRK9oAm', 'canniwell2c', 'Carri', 'Anniwell', '4683 Lakewood Gardens Drive', '4143268625', 1.95);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('kgillie2d@elegantthemes.com', 'qx07XbV7y', 'kgillie2d', 'Kellia', 'Gillie', '002 Lake View Junction', '7934453893', 0.75);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('vdy2e@globo.com', 'EdGzMBcKxOn', 'vdy2e', 'Vaughan', 'Dy', '56 Dixon Park', '1416157358', 1.93);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('lcapponer2f@hubpages.com', 'doB1Prb', 'lcapponer2f', 'Laurene', 'Capponer', '7397 Trailsway Place', '2257711164', 1.61);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('jmacari2g@t-online.de', 'rr5rwotLFCKL', 'jmacari2g', 'Jeanne', 'Macari', '17 Monument Court', '7877309432', 2.17);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('smoulton2h@webnode.com', '7SfeM8LUJfZ8', 'smoulton2h', 'Stevie', 'Moulton', '9979 Nobel Place', '7677981245', 0.7);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('tcrum2i@a8.net', '9smVQFLbJgE', 'tcrum2i', 'Truman', 'Crum', '04532 Clyde Gallagher Junction', '7767770558', 0.88);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('jmenichini2j@seattletimes.com', 'mBWm59', 'jmenichini2j', 'Justis', 'Menichini', '2 Darwin Pass', '8465484187', 2.43);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('sjovasevic2k@cmu.edu', 'tUBRdj7V', 'sjovasevic2k', 'Saunder', 'Jovasevic', '0 Kinsman Plaza', '6937988131', 3.78);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('dmcclintock2l@boston.com', 'z2APMkzXg5OM', 'dmcclintock2l', 'Dasya', 'McClintock', '26866 Melody Park', '7335647533', 1.06);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('aborgars2m@hao123.com', 'T8ZvQ7WeG0Q', 'aborgars2m', 'Aguistin', 'Borgars', '3 Hazelcrest Court', '9834480109', 4.26);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('hskoggins2n@studiopress.com', 'xHew8v', 'hskoggins2n', 'Hughie', 'Skoggins', '2286 Wayridge Plaza', '9094148277', 0.72);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('smacallister2o@npr.org', 'x7si0hlm', 'smacallister2o', 'Sybyl', 'MacAllister', '5 Steensland Parkway', '4263658092', 0.72);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('gmcreath2p@time.com', '0szwCaR98DxE', 'gmcreath2p', 'Gaby', 'McReath', '944 American Pass', '9862137506', 2.64);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('fnabarro2q@acquirethisname.com', 'rADCd3v', 'fnabarro2q', 'Felike', 'Nabarro', '912 Sunbrook Avenue', '2906057854', 4.79);
insert into user (email, password, username, first_name, last_name, address, phone, rating) values ('ssterry2r@barnesandnoble.com', 'Z07zdgjn', 'ssterry2r', 'Syd', 'Sterry', '145 Sycamore Street', '3406022397', 4.23);

-- SET @PROJDIR = '/home/vineetkumar19/Desktop/ecom/ArtPoint/';
SET @PROJDIR = '/home/genericspecimen/repos';
insert into art (title, description, price, image_location) values ('Bird of Paradise', 'Other physeal fracture of lower end of humerus, left arm, sequela', 8374.07, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/1.png'));
insert into art (title, description, price, image_location) values ('Enduring Love', 'Unspecified superficial injury of unspecified forearm, initial encounter', 6204.08, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/2.png'));
insert into art (title, description, price, image_location) values ('Anchorman 2: The Legend Continues', 'Adverse effect of loop [high-ceiling] diuretics, initial encounter', 7579.35, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/3.png'));
insert into art (title, description, price, image_location) values ('Dave Chappelle: For What it''s Worth', 'Other superficial injuries of unspecified thumb, initial encounter', 8238.8, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/4.png'));
insert into art (title, description, price, image_location) values ('Force Majeure (Turist)', 'Displaced fracture of fifth metatarsal bone, right foot, sequela', 7043.56, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/5.png'));
insert into art (title, description, price, image_location) values ('Month by the Lake, A', 'Nondisplaced fracture of neck of other metacarpal bone', 2943.46, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/6.png'));
insert into art (title, description, price, image_location) values ('Testament', 'Other acquired deformities of limbs', 9679.54, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/7.png'));
insert into art (title, description, price, image_location) values ('Breaking In', 'Person on outside of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus in nontraffic accident, sequela', 3995.68, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/8.png'));
insert into art (title, description, price, image_location) values ('Days and Nights in the Forest (Aranyer Din Ratri)', 'Displaced fracture of lower epiphysis (separation) of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 4943.47, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/9.png'));
insert into art (title, description, price, image_location) values ('Grown Ups', 'Subluxation of lens, bilateral', 6977.52, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/10.png'));
insert into art (title, description, price, image_location) values ('Why Be Good?', 'Fall into hole', 9924.36, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/10.png'));
insert into art (title, description, price, image_location) values ('Born to Raise Hell', 'Displaced segmental fracture of shaft of left tibia, subsequent encounter for closed fracture with malunion', 4448.04, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/11.png'));
insert into art (title, description, price, image_location) values ('Fat Man and Little Boy', 'Narcissistic personality disorder', 2252.45, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/12.png'));
insert into art (title, description, price, image_location) values ('Last Man, The', 'Corrosion of first degree of multiple sites of left wrist and hand', 6325.13, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/13.png'));
insert into art (title, description, price, image_location) values ('Prisoner of Paradise', 'Other meniscus derangements, other lateral meniscus, right knee', 1084.04, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/14.png'));
insert into art (title, description, price, image_location) values ('Enforcer, The', 'Other anterior subluxation of right hip, subsequent encounter', 7795.32, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/15.png'));
insert into art (title, description, price, image_location) values ('Footprints of a Spirit, The (Huellas de un espíritu)', 'Other fracture of fifth lumbar vertebra, sequela', 3310.97, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/16.png'));
insert into art (title, description, price, image_location) values ('Inserts', 'Other specified injury of dorsal artery of right foot, subsequent encounter', 18.08, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/17.png'));
insert into art (title, description, price, image_location) values ('Hotel Rwanda', 'Hypertrophy of bone, unspecified shoulder', 7287.84, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/18.png'));
insert into art (title, description, price, image_location) values ('Leviathan', 'Algoneurodystrophy, left upper arm', 7346.86, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/19.png'));
insert into art (title, description, price, image_location) values ('Space Odyssey: Voyage to the Planets', 'Pedal cycle driver injured in collision with other nonmotor vehicle in nontraffic accident, initial encounter', 9839.33, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/20.png'));
insert into art (title, description, price, image_location) values ('Role/Play', 'Vascular disorder of intestine, unspecified', 9294.41, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/21.png'));
insert into art (title, description, price, image_location) values ('Casual Sex?', 'Other fracture of upper end of ulna', 2566.34, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/22.png'));
insert into art (title, description, price, image_location) values ('Room in Rome (Habitación en Roma)', 'Laceration of unspecified Achilles tendon, initial encounter', 3115.29, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/23.png'));
insert into art (title, description, price, image_location) values ('She''s So Lovely', 'Displaced fracture of shaft of fifth metacarpal bone, right hand, sequela', 4620.43, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/24.png'));
insert into art (title, description, price, image_location) values ('Band''s Visit, The (Bikur Ha-Tizmoret)', 'Adjustment disorder with other symptoms', 5657.94, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/25.png'));
insert into art (title, description, price, image_location) values ('LOL', 'Nondisplaced fracture of fourth metatarsal bone, right foot, subsequent encounter for fracture with delayed healing', 7143.48, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/26.png'));
insert into art (title, description, price, image_location) values ('Extremities', 'Laceration of intercostal blood vessels, right side', 5644.48, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/27.png'));
insert into art (title, description, price, image_location) values ('Prisoner, The (Island of Fire) (Huo shao dao)', 'Open bite, left ankle, sequela', 8705.86, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/28.png'));
insert into art (title, description, price, image_location) values ('I Knew It Was You: Rediscovering John Cazale', '4-part fracture of surgical neck of unspecified humerus, sequela', 6022.88, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/29.png'));
insert into art (title, description, price, image_location) values ('Dear White People', 'Nondisplaced spiral fracture of shaft of left fibula, sequela', 4085.97, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/30.png'));
insert into art (title, description, price, image_location) values ('Kanak Attack', 'Laceration of other blood vessels at lower leg level, unspecified leg, subsequent encounter', 4788.89, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/31.png'));
insert into art (title, description, price, image_location) values ('Vinyan', 'Interstitial and deep keratitis', 794.1, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/32.png'));
insert into art (title, description, price, image_location) values ('Rough House, The', 'Nondisplaced fracture of medial cuneiform of left foot, initial encounter for open fracture', 3853.12, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/33.png'));
insert into art (title, description, price, image_location) values ('Wind, The', 'Acute lymphadenitis of other sites', 6782.12, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/34.png'));
insert into art (title, description, price, image_location) values ('Christopher Strong', 'Acute nasopharyngitis [common cold]', 2225.88, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/35.png'));
insert into art (title, description, price, image_location) values ('Adventures of Don Juan', 'Injury of left internal carotid artery, intracranial portion, not elsewhere classified with loss of consciousness of 6 hours to 24 hours', 8397.79, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/36.png'));
insert into art (title, description, price, image_location) values ('Woman Rebels, A (Portrait of a Rebel)', 'Contusion, laceration, and hemorrhage of brainstem with loss of consciousness greater than 24 hours with return to pre-existing conscious level, sequela', 6290.1, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/37.png'));
insert into art (title, description, price, image_location) values ('Beautician and the Beast, The', 'Intentional self-harm by exposure to extremes of cold, initial encounter', 3392.96, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/38.png'));
insert into art (title, description, price, image_location) values ('Innocent Voices (Voces inocentes)', 'Acute lymphangitis of unspecified part of limb', 2776.3, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/39.png'));
insert into art (title, description, price, image_location) values ('Cry in the Night, A', 'Mycotic corneal ulcer', 5636.79, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/40.png'));
insert into art (title, description, price, image_location) values ('Alaska: Silence & Solitude', 'Fracture of unspecified phalanx of left little finger, subsequent encounter for fracture with malunion', 4065.33, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/41.png'));
insert into art (title, description, price, image_location) values ('Next of Kin', 'Forced landing of commercial fixed-wing aircraft injuring occupant, subsequent encounter', 7678.8, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/42.png'));
insert into art (title, description, price, image_location) values ('Ninja Scroll (Jûbei ninpûchô)', 'Other specified disorders of synovium, left shoulder', 5182.92, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/43.png'));
insert into art (title, description, price, image_location) values ('Murder in Coweta County', 'Laceration of left kidney, unspecified degree', 2242.82, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/44.png'));
insert into art (title, description, price, image_location) values ('Roger & Me', 'Burn of unspecified eyelid and periocular area, subsequent encounter', 6517.14, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/45.png'));
insert into art (title, description, price, image_location) values ('All Relative', 'Osteitis deformans in neoplastic diseases, right upper arm', 3956.67, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/46.png'));
insert into art (title, description, price, image_location) values ('Illustrious Corpses (Cadaveri eccellenti)', 'Combined forms of infantile and juvenile cataract, right eye', 5236.91, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/47.png'));
insert into art (title, description, price, image_location) values ('Cartoon All-Stars to the Rescue', 'Unspecified fracture of lower end of left humerus, sequela', 3041.67, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/48.png'));
insert into art (title, description, price, image_location) values ('Miss Kicki', 'Corrosion of unspecified degree of right elbow, sequela', 6790.97, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/49.png'));
insert into art (title, description, price, image_location) values ('One Nite In Mongkok (Wong gok hak yau)', 'Other superficial bite of left ring finger, sequela', 3277.18, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/50.png'));
insert into art (title, description, price, image_location) values ('Black Dragons', 'Neoplasm of uncertain behavior of the sublingual salivary glands', 5746.05, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/51.png'));
insert into art (title, description, price, image_location) values ('Animals are Beautiful People', 'Displaced fracture of medial phalanx of left index finger, initial encounter for closed fracture', 664.82, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/52.png'));
insert into art (title, description, price, image_location) values ('Stargate: Continuum', 'Corrosion of unspecified degree of nose (septum), subsequent encounter', 3928.61, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/53.png'));
insert into art (title, description, price, image_location) values ('Toy, The (Le jouet)', 'Antepartum hemorrhage with coagulation defect', 6586.18, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/54.png'));
insert into art (title, description, price, image_location) values ('Command Performance', 'Paralytic calcification and ossification of muscle, shoulder', 7355.07, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/55.png'));
insert into art (title, description, price, image_location) values ('Batman and Robin', 'Nondisplaced fracture of posterior wall of left acetabulum, subsequent encounter for fracture with nonunion', 2586.84, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/56.png'));
insert into art (title, description, price, image_location) values ('Harmony and Me', 'Nondisplaced fracture of neck of scapula, right shoulder, subsequent encounter for fracture with routine healing', 283.69, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/57.png'));
insert into art (title, description, price, image_location) values ('Rachel, Rachel', 'Fibrosis due to genitourinary prosthetic devices, implants and grafts, initial encounter', 2060.56, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/58.png'));
insert into art (title, description, price, image_location) values ('Ikiru', 'Other specified injury of deep palmar arch of left hand, sequela', 6727.05, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/59.png'));
insert into art (title, description, price, image_location) values ('Stille nacht', 'Pre-existing secondary hypertension complicating pregnancy', 6810.22, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/60.png'));
insert into art (title, description, price, image_location) values ('Drive Me Crazy', 'Insect bite (nonvenomous), right great toe, sequela', 5687.37, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/61.png'));
insert into art (title, description, price, image_location) values ('Witches, The (aka Devil''s Own, The)', 'Nondisplaced bimalleolar fracture of left lower leg, subsequent encounter for closed fracture with routine healing', 2199.82, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/62.png'));
insert into art (title, description, price, image_location) values ('Sherlock Holmes in Washington', 'Perforation due to foreign body accidentally left in body following other procedure, sequela', 6197.24, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/63.png'));
insert into art (title, description, price, image_location) values ('Darwin''s Nightmare', 'Superficial foreign body of left ear, sequela', 3386.74, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/64.png'));
insert into art (title, description, price, image_location) values ('Lammbock', 'Maternal care for other isoimmunization, third trimester, fetus 3', 5111.36, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/65.png'));
insert into art (title, description, price, image_location) values ('ThanksKilling 3 ', 'Unspecified injury of bronchus, unilateral', 7031.45, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/66.png'));
insert into art (title, description, price, image_location) values ('Dummy', 'Poisoning by antithyroid drugs, intentional self-harm', 7164.44, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/67.png'));
insert into art (title, description, price, image_location) values ('Scooby-Doo 2: Monsters Unleashed', 'Unspecified injury of flexor muscle, fascia and tendon of left middle finger at wrist and hand level, sequela', 4420.21, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/68.png'));
insert into art (title, description, price, image_location) values ('More Than a Game', 'Strain of extensor muscle, fascia and tendon of unspecified finger at wrist and hand level, subsequent encounter', 7645.1, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/69.png'));
insert into art (title, description, price, image_location) values ('Mud', 'Unspecified injury of other blood vessels at ankle and foot level, right leg, sequela', 3902.02, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/70.png'));
insert into art (title, description, price, image_location) values ('Piano in a Factory, The (Gang de qin)', 'Barton''s fracture of right radius, initial encounter for closed fracture', 1365.16, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/71.png'));
insert into art (title, description, price, image_location) values ('Command Performance', 'Injury of cutaneous sensory nerve at forearm level, right arm, sequela', 7321.3, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/72.png'));
insert into art (title, description, price, image_location) values ('Inherit the Wind', 'Displaced other fracture of tuberosity of left calcaneus, subsequent encounter for fracture with malunion', 2257.03, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/73.png'));
insert into art (title, description, price, image_location) values ('Little World of Don Camillo, The (Petit monde de Don Camillo, Le)', 'Other fracture of patella', 5776.32, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/74.png'));
insert into art (title, description, price, image_location) values ('Mission: Impossible II', 'Bus occupant (driver) (passenger) injured in other specified transport accidents', 1366.62, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/75.png'));
insert into art (title, description, price, image_location) values ('Lolita', 'Galeazzi''s fracture of left radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', 3854.26, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/76.png'));
insert into art (title, description, price, image_location) values ('Aqua Teen Hunger Force Colon Movie Film for Theaters', 'Nondisplaced fracture of fourth metatarsal bone, unspecified foot, subsequent encounter for fracture with delayed healing', 4903.42, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/77.png'));
insert into art (title, description, price, image_location) values ('Bigga Than Ben', 'Anterior dislocation of right humerus, sequela', 1594.88, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/78.png'));
insert into art (title, description, price, image_location) values ('Reclaim Your Brain (Free Rainer)', 'Bus occupant (driver) (passenger) injured in unspecified traffic accident, sequela', 2195.88, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/79.png'));
insert into art (title, description, price, image_location) values ('Willow Tree, The (Beed-e majnoon)', 'Laceration of diaphragm, initial encounter', 4658.28, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/80.png'));
insert into art (title, description, price, image_location) values ('Spirit of the Beehive, The (Espíritu de la colmena, El)', 'Diverticulitis of both small and large intestine with perforation and abscess with bleeding', 6180.41, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/81.png'));
insert into art (title, description, price, image_location) values ('Courage Mountain', 'Phlebitis and thrombophlebitis of popliteal vein, bilateral', 3771.82, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/82.png'));
insert into art (title, description, price, image_location) values ('Sagebrush Trail', 'Preterm labor third trimester with preterm delivery third trimester, other fetus', 7124.86, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/83.png'));
insert into art (title, description, price, image_location) values ('Red Flag', 'Nondisplaced spiral fracture of shaft of radius, unspecified arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 600.46, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/84.png'));
insert into art (title, description, price, image_location) values ('Ex, The', 'Complete lesion at C5 level of cervical spinal cord, sequela', 7468.39, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/85.png'));
insert into art (title, description, price, image_location) values ('Fast Times at Ridgemont High', 'Other fracture of lower end of left tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 8702.64, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/86.png'));
insert into art (title, description, price, image_location) values ('Twelfth Night', 'Adverse effect of antimalarials and drugs acting on other blood protozoa', 1267.38, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/87.png'));
insert into art (title, description, price, image_location) values ('Way, The', 'Abrasion of ankle', 9892.25, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/88.png'));
insert into art (title, description, price, image_location) values ('Jersey Girl', 'External constriction of unspecified external genital organs, male, sequela', 8867.31, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/89.png'));
insert into art (title, description, price, image_location) values ('Rosalie Goes Shopping', 'Strain of intrinsic muscle, fascia and tendon of left middle finger at wrist and hand level, sequela', 7598.07, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/90.png'));
insert into art (title, description, price, image_location) values ('Charlie Countryman', 'Poisoning by, adverse effect of and underdosing of enzymes', 1240.05, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/91.png'));
insert into art (title, description, price, image_location) values ('Samurai Banners (Fûrin kazan)', 'Pathological fracture in other disease, unspecified tibia and fibula, subsequent encounter for fracture with delayed healing', 1253.12, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/92.png'));
insert into art (title, description, price, image_location) values ('Fistful of Fingers, A', 'Calcification and ossification of muscles associated with burns, unspecified lower leg', 1748.77, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/93.png'));
insert into art (title, description, price, image_location) values ('Kevin Smith: Burn in Hell', 'Unspecified motorcycle rider injured in collision with car, pick-up truck or van in traffic accident, subsequent encounter', 9006.81, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/94.png'));
insert into art (title, description, price, image_location) values ('Snake and Mongoose', 'Accidental discharge of paintball gun, sequela', 672.17, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/95.png'));
insert into art (title, description, price, image_location) values ('Sisters, The', 'Pigmentary glaucoma, right eye, stage unspecified', 913.66, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/96.png'));
insert into art (title, description, price, image_location) values ('Gamera vs. Gyaos (Daikaijû kûchûsen: Gamera tai Gyaosu)', 'Trichomoniasis, unspecified', 1017.56, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/97.png'));
insert into art (title, description, price, image_location) values ('Good-bye, My Lady', 'Mechanical loosening of internal right hip prosthetic joint, sequela', 4007.68, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/98.png'));
insert into art (title, description, price, image_location) values ('Marley & Me: The Puppy Years', 'Rheumatoid lung disease with rheumatoid arthritis of right wrist', 7507.95, CONCAT(@PROJDIR, '/art-point/backend/art-point/target/classes/static/images/99.png'));

update art
set owner_id = 1
where id between 1 and 50;

update art
set owner_id = 2
where id between 51 and 100;

--insert into ORDER_TABLE (buyer_id) values (3);
--insert into ORDER_TABLE (buyer_id) values (2);
--insert into ORDER_TABLE (buyer_id) values (3);
--insert into ORDER_TABLE (buyer_id) values (10);
--insert into ORDER_TABLE (buyer_id) values (8);
--insert into ORDER_TABLE (buyer_id) values (4);
--insert into ORDER_TABLE (buyer_id) values (9);
--insert into ORDER_TABLE (buyer_id) values (10);
--insert into ORDER_TABLE (buyer_id) values (6);
--insert into ORDER_TABLE (buyer_id) values (2);
--insert into ORDER_TABLE (buyer_id) values (6);
--insert into ORDER_TABLE (buyer_id) values (4);
--insert into ORDER_TABLE (buyer_id) values (10);
--insert into ORDER_TABLE (buyer_id) values (4);
--insert into ORDER_TABLE (buyer_id) values (4);
--insert into ORDER_TABLE (buyer_id) values (4);
--insert into ORDER_TABLE (buyer_id) values (7);
--insert into ORDER_TABLE (buyer_id) values (7);
--insert into ORDER_TABLE (buyer_id) values (1);
--insert into ORDER_TABLE (buyer_id) values (2);
--
--insert into ORDER_ART (order_id, art_id, quantity) values (1, 71, 6);
--insert into ORDER_ART (order_id, art_id, quantity) values (2, 90, 4);
--insert into ORDER_ART (order_id, art_id, quantity) values (3, 55, 2);
--insert into ORDER_ART (order_id, art_id, quantity) values (4, 20, 10);
--insert into ORDER_ART (order_id, art_id, quantity) values (5, 86, 9);
--insert into ORDER_ART (order_id, art_id, quantity) values (6, 55, 7);
--insert into ORDER_ART (order_id, art_id, quantity) values (7, 17, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (8, 100, 6);
--insert into ORDER_ART (order_id, art_id, quantity) values (9, 32, 1);
--insert into ORDER_ART (order_id, art_id, quantity) values (10, 81, 9);
--insert into ORDER_ART (order_id, art_id, quantity) values (11, 16, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (12, 88, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (13, 21, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (14, 84, 7);
--insert into ORDER_ART (order_id, art_id, quantity) values (15, 57, 10);
--insert into ORDER_ART (order_id, art_id, quantity) values (16, 10, 1);
--insert into ORDER_ART (order_id, art_id, quantity) values (17, 3, 10);
--insert into ORDER_ART (order_id, art_id, quantity) values (18, 69, 7);
--insert into ORDER_ART (order_id, art_id, quantity) values (19, 97, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (20, 37, 10);
--insert into ORDER_ART (order_id, art_id, quantity) values (1, 27, 10);
--insert into ORDER_ART (order_id, art_id, quantity) values (9, 21, 1);
--insert into ORDER_ART (order_id, art_id, quantity) values (11, 42, 3);
--insert into ORDER_ART (order_id, art_id, quantity) values (11, 96, 9);
--insert into ORDER_ART (order_id, art_id, quantity) values (5, 59, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (6, 2, 9);
--insert into ORDER_ART (order_id, art_id, quantity) values (12, 47, 9);
--insert into ORDER_ART (order_id, art_id, quantity) values (13, 91, 1);
----insert into ORDER_ART (order_id, art_id, quantity) values (12, 88, 2);
--insert into ORDER_ART (order_id, art_id, quantity) values (7, 63, 3);
--insert into ORDER_ART (order_id, art_id, quantity) values (1, 22, 7);
--insert into ORDER_ART (order_id, art_id, quantity) values (7, 18, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (7, 96, 4);
--insert into ORDER_ART (order_id, art_id, quantity) values (12, 42, 3);
--insert into ORDER_ART (order_id, art_id, quantity) values (16, 76, 9);
--insert into ORDER_ART (order_id, art_id, quantity) values (7, 99, 4);
--insert into ORDER_ART (order_id, art_id, quantity) values (2, 41, 7);
--insert into ORDER_ART (order_id, art_id, quantity) values (12, 70, 5);
--insert into ORDER_ART (order_id, art_id, quantity) values (7, 9, 6);
--insert into ORDER_ART (order_id, art_id, quantity) values (7, 58, 7);
--insert into ORDER_ART (order_id, art_id, quantity) values (11, 35, 4);
--insert into ORDER_ART (order_id, art_id, quantity) values (8, 63, 1);
--insert into ORDER_ART (order_id, art_id, quantity) values (17, 15, 7);
--insert into ORDER_ART (order_id, art_id, quantity) values (19, 71, 1);
--insert into ORDER_ART (order_id, art_id, quantity) values (2, 26, 2);
--insert into ORDER_ART (order_id, art_id, quantity) values (18, 100, 4);
--insert into ORDER_ART (order_id, art_id, quantity) values (20, 32, 5);
--insert into ORDER_ART (order_id, art_id, quantity) values (3, 29, 8);
--insert into ORDER_ART (order_id, art_id, quantity) values (11, 72, 4);
--insert into ORDER_ART (order_id, art_id, quantity) values (12, 72, 10);

insert into category (name) values ('architecture');
insert into category (name) values ('ceramics');
insert into category (name) values ('drawing');
insert into category (name) values ('painting');
insert into category (name) values ('photography');
insert into category (name) values ('sculpture');

-- insert into art_categories values (1, 'sculpture');
-- insert into art_categories values (1, 'painting');
